a=input('Digite algo: ')
print(f'O tipo primitivo desse valor é: ', type(a))
print('só tem espaços? ', a.isspace())
print('é um número? ', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumérico?', a.isalnum())
print('está em maiusculo?', a.isupper())
print('está em minusculo?', a.islower())
